#!/usr/bin/env python3
"""Wire-shape baseline refresher.

Walks the same comparison the validator does and writes the result to
tests/fixtures/wire-shape-baseline.json. Use when a SHA bump or
deliberate burndown changes the expected drift set.

Usage:
  python3 scripts/wire-shape/refresh.py <specs_dir> [--sha <SHA>]

If --sha is omitted, attempts `git -C <specs_dir> rev-parse HEAD`.
Exits non-zero rather than write a baseline with empty SHA.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lib  # noqa: E402


def _git_head_sha(specs_dir: Path) -> str:
    git = shutil.which("git")
    if git is None:
        return ""
    try:
        out = subprocess.run(  # noqa: S603 - absolute git path, fixed args
            [git, "-C", str(specs_dir), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            timeout=5,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError):
        return ""
    return out.stdout.strip()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("specs_dir", type=Path)
    parser.add_argument("--sha", type=str, default=None)
    args = parser.parse_args()

    specs_dir: Path = args.specs_dir
    if not specs_dir.is_dir():
        print(f"error: {specs_dir} is not a directory", file=sys.stderr)
        return 2

    sha = args.sha if args.sha else _git_head_sha(specs_dir)
    if not sha:
        print(
            "error: could not determine OpenAPI specs commit SHA. Pass --sha <SHA> "
            "or run against a specs_dir inside a git checkout of "
            "getaxonflow/axonflow. An empty SHA would poison the baseline.",
            file=sys.stderr,
        )
        return 2

    plugin_reads = lib.discover_plugin_reads(lib.SCRIPTS_DIR)
    schemas = lib.load_schemas(specs_dir)
    drift, unmapped = lib.compute_drift(plugin_reads, schemas)

    out = {
        "_comment": (
            "Baseline of KNOWN wire-shape drift between the AxonFlow Claude Code "
            "plugin's MCP-response field reads and the AxonFlow agent OpenAPI "
            "spec at openapi_specs_sha. The CI gate fails on drift OUTSIDE this "
            "baseline. Entries here should be burned down over time via targeted "
            "PRs that either (a) update the bash script to match the spec, "
            "(b) update the spec to document the missing fields (file platform-"
            "side), or (c) recognize the field as @sdkDerived if it's a plugin-"
            "side derivation. Generated by scripts/wire-shape/refresh.py."
        ),
        "openapi_specs_sha": sha,
        "registered_schemas": sorted(lib.MCP_RESULT_VARS.values()),
        "plugin_reads": {schema: sorted(fields) for schema, fields in plugin_reads.items()},
        "per_type_drift": dict(sorted(drift.items())),
        "unmapped_in_spec": sorted(unmapped),
    }

    lib.write_baseline(out)

    print(f"Wrote baseline: {lib.BASELINE_PATH}")
    print(f"  openapi_specs_sha:   {sha}")
    print(f"  registered_schemas:  {len(lib.MCP_RESULT_VARS)}")
    print(f"  per_type_drift:      {len(drift)}")
    print(f"  unmapped_in_spec:    {len(unmapped)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
